name: Publish on GitHub
 
on:
  push:
    branches: [ master ]
    paths: [ 'src/**' ]
  workflow_dispatch:

env:
  NET_VERSION: '6.x'
  PROJECT_NAME: src/GestioneSagre.Web.Server
  PROJECT_FILE: GestioneSagre.Web.Server.csproj
  
jobs:
  build:
    name: Publish on GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}
        
    - name: Package
      run: dotnet pack -c Release -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'
      
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v${{ steps.nbgv.outputs.NuGetPackageVersion }}
          release_name: ver. ${{ steps.nbgv.outputs.NuGetPackageVersion }} preview
          draft: false
          prerelease: false
